---
- name: Set vlan
  connection: local
  hosts: vthunder  
  tasks:
  - name: Set Vlan 
    a10.acos_axapi.a10_network_vlan:
      state: present
      ansible_host: "{{ ansible_host }}"
      ansible_username: "{{ a10_username }}"
      ansible_password: "{{ a10_password }}"
      ansible_port: "{{ a10_port }}"
      vlan_num: "{{ a10_outside_vlan }}"
      name: "{{ a10_outside_name }}"
      untagged_eth_list:
        - untagged_ethernet_start: "{{ a10_outside_interface }}"
          untagged_ethernet_end: "{{ a10_outside_interface }}"
      ve: "{{ a10_outside_vlan }}"

